"""empty message

Revision ID: 17a9399d0aa6
Revises: d1068a8e4483
Create Date: 2025-01-27 21:49:14.436464

"""
import random
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
from sqlalchemy.orm import Session

from src.database.models.aviso import Aviso
from src.database.models.categoria import Categoria
from src.database.models.musica import Musica
from src.database.models.notificacao import Notificacao
from src.database.models.usuario import Usuario
from src.database.models.usuario_aviso import UsuarioAviso
from src.utils.enums import TipoUsuarioEnum

# Import your models

# revision identifiers, used by Alembic.
revision: str = "17a9399d0aa6"
down_revision: Union[str, None] = "d1068a8e4483"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    session = Session(bind=bind)
    entries_per_table = 5000

    # Insert Usuarios
    session.bulk_save_objects(
        [
            Usuario(
                id=index,
                nome=f"Usuario {_uuid}",
                email=f"{_uuid}@gmail.com",
                senha=f"{_uuid}",
                tipo_usuario=TipoUsuarioEnum.PADRAO,
            )
            for _uuid, index in (
                (uuid4(), index) for index in range(1, entries_per_table + 1)
            )
        ]
    )

    # Insert Categoria
    session.bulk_save_objects(
        [
            Categoria(
                id=index,
                nome=f"Categoria {uuid4()}",
                descricao=f"Categoria exemplo {index}.",
            )
            for index in range(1, entries_per_table + 1)
        ]
    )

    # Insert Musicas
    session.bulk_save_objects(
        [
            Musica(
                id=index,
                nome=f"Musica {uuid4()}",
                letra=f"{uuid4()}" * 5,
                fk_Categoria_id=random.randint(1, entries_per_table),
                fk_Usuarios_id=random.randint(1, entries_per_table),
            )
            for index in range(1, entries_per_table + 1)
        ]
    )

    # # Insert Notificacoes
    session.bulk_save_objects(
        [
            Notificacao(
                id=index,
                titulo=f"Notificacao {uuid4()}",
                fk_Usuarios_id=random.randint(1, entries_per_table),
            )
            for index in range(1, entries_per_table + 1)
        ]
    )

    # # Insert Avisos
    session.bulk_save_objects(
        [
            Aviso(id=index, titulo=f"Aviso {uuid4()}", texto=f"{uuid4()}" * 5)
            for index in range(1, entries_per_table + 1)
        ]
    )

    # # Insert UsuarioAviso
    session.bulk_save_objects(
        [
            UsuarioAviso(
                id=index,
                fk_Avisos_id=random.randint(1, entries_per_table),
                fk_Usuarios_id=random.randint(1, entries_per_table),
            )
            for index in range(1, entries_per_table + 1)
        ]
    )

    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
