"""Criação das tabelas, colunas, relações e constraints

Revision ID: 9937098d2ec1
Revises:
Create Date: 2025-01-04 16:55:10.999042

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9937098d2ec1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "autores",
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("escalada", sa.String(length=255), nullable=True),
        sa.Column("numeracao_da_escalada", sa.Integer(), nullable=True),
        sa.Column("local_da_escalada", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_autores_id"), "autores", ["id"], unique=False)
    op.create_table(
        "musicas",
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("letra", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_musicas_id"), "musicas", ["id"], unique=False)
    op.create_table(
        "usuarios",
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("senha", sa.String(length=255), nullable=False),
        sa.Column(
            "tipo_usuario",
            sa.Enum("ADMIN", "PADRAO", name="tipousuarioenum"),
            nullable=False,
        ),
        sa.Column("token_reset_senha", sa.String(length=5), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_usuarios_email"), "usuarios", ["email"], unique=False)
    op.create_index(op.f("ix_usuarios_id"), "usuarios", ["id"], unique=False)
    op.create_table(
        "autor_musica",
        sa.Column("musica_id", sa.Integer(), nullable=False),
        sa.Column("autor_id", sa.Integer(), nullable=False),
        sa.Column("papel", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["autor_id"],
            ["autores.id"],
        ),
        sa.ForeignKeyConstraint(
            ["musica_id"],
            ["musicas.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_autor_musica_id"), "autor_musica", ["id"], unique=False)
    op.create_index(
        op.f("ix_autor_musica_papel"), "autor_musica", ["papel"], unique=False
    )
    op.create_table(
        "avisos",
        sa.Column("criador_id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("texto", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["criador_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_avisos_criador_id"), "avisos", ["criador_id"], unique=False
    )
    op.create_index(op.f("ix_avisos_id"), "avisos", ["id"], unique=False)
    op.create_table(
        "fotos",
        sa.Column("criador_id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=True),
        sa.Column("descricao", sa.String(length=4096), nullable=True),
        sa.Column("url", sa.String(length=4096), nullable=False),
        sa.Column("ativo", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["criador_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fotos_criador_id"), "fotos", ["criador_id"], unique=False)
    op.create_index(op.f("ix_fotos_id"), "fotos", ["id"], unique=False)
    op.create_table(
        "gerar_acesso_admin",
        sa.Column("token", sa.UUID(), nullable=False),
        sa.Column("expira_em", sa.DateTime(), nullable=False),
        sa.Column("descricao", sa.String(length=255), nullable=True),
        sa.Column("criador_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["criador_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gerar_acesso_admin_criador_id"),
        "gerar_acesso_admin",
        ["criador_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gerar_acesso_admin_id"), "gerar_acesso_admin", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_gerar_acesso_admin_token"),
        "gerar_acesso_admin",
        ["token"],
        unique=True,
    )
    op.create_table(
        "historico_edicoes_dashboard",
        sa.Column("editor_id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("texto", sa.String(length=4096), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["editor_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_historico_edicoes_dashboard_editor_id"),
        "historico_edicoes_dashboard",
        ["editor_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historico_edicoes_dashboard_id"),
        "historico_edicoes_dashboard",
        ["id"],
        unique=False,
    )
    op.create_table(
        "notificacoes",
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("visto_em", sa.Date(), nullable=True),
        sa.Column("texto", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_notificacoes_id"), "notificacoes", ["id"], unique=False)
    op.create_index(
        op.f("ix_notificacoes_usuario_id"), "notificacoes", ["usuario_id"], unique=False
    )
    op.create_table(
        "solicitacoes_de_musica",
        sa.Column("solicitante_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDENTE", "ACEITA", "RECUSADA", name="statussolicitacaodemusicaenum"
            ),
            nullable=False,
        ),
        sa.Column(
            "tipo_solicitacao",
            sa.Enum(
                "CRIAR", "ATUALIZAR", "REMOVER", name="tiposolicitacaodemusicaenum"
            ),
            nullable=False,
        ),
        sa.Column("avaliador_id", sa.Integer(), nullable=True),
        sa.Column("avaliado_em", sa.Date(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "(avaliador_id IS NOT NULL AND avaliado_em IS NOT NULL) OR (avaliador_id IS NULL AND avaliado_em IS NULL)",
            name="check_avaliador_and_avaliado_em",
        ),
        sa.ForeignKeyConstraint(
            ["avaliador_id"],
            ["usuarios.id"],
        ),
        sa.ForeignKeyConstraint(
            ["solicitante_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_solicitacoes_de_musica_id"),
        "solicitacoes_de_musica",
        ["id"],
        unique=False,
    )
    op.create_table(
        "foto_historico_edicoes_dashboard",
        sa.Column("historico_edicao_dashboard_id", sa.Integer(), nullable=False),
        sa.Column("foto_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["foto_id"],
            ["fotos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["historico_edicao_dashboard_id"],
            ["historico_edicoes_dashboard.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_foto_historico_edicoes_dashboard_id"),
        "foto_historico_edicoes_dashboard",
        ["id"],
        unique=False,
    )
    op.create_table(
        "usuario_foto",
        sa.Column("usuario_id", sa.Integer(), nullable=False),
        sa.Column("foto_id", sa.Integer(), nullable=False),
        sa.Column("principal", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["foto_id"],
            ["fotos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["usuario_id"],
            ["usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("usuario_id", "principal", name="uq_usuario_principal"),
    )
    op.create_index(op.f("ix_usuario_foto_id"), "usuario_foto", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usuario_foto_id"), table_name="usuario_foto")
    op.drop_table("usuario_foto")
    op.drop_index(
        op.f("ix_foto_historico_edicoes_dashboard_id"),
        table_name="foto_historico_edicoes_dashboard",
    )
    op.drop_table("foto_historico_edicoes_dashboard")
    op.drop_index(
        op.f("ix_solicitacoes_de_musica_id"), table_name="solicitacoes_de_musica"
    )
    op.drop_table("solicitacoes_de_musica")
    op.drop_index(op.f("ix_notificacoes_usuario_id"), table_name="notificacoes")
    op.drop_index(op.f("ix_notificacoes_id"), table_name="notificacoes")
    op.drop_table("notificacoes")
    op.drop_index(
        op.f("ix_historico_edicoes_dashboard_id"),
        table_name="historico_edicoes_dashboard",
    )
    op.drop_index(
        op.f("ix_historico_edicoes_dashboard_editor_id"),
        table_name="historico_edicoes_dashboard",
    )
    op.drop_table("historico_edicoes_dashboard")
    op.drop_index(op.f("ix_gerar_acesso_admin_token"), table_name="gerar_acesso_admin")
    op.drop_index(op.f("ix_gerar_acesso_admin_id"), table_name="gerar_acesso_admin")
    op.drop_index(
        op.f("ix_gerar_acesso_admin_criador_id"), table_name="gerar_acesso_admin"
    )
    op.drop_table("gerar_acesso_admin")
    op.drop_index(op.f("ix_fotos_id"), table_name="fotos")
    op.drop_index(op.f("ix_fotos_criador_id"), table_name="fotos")
    op.drop_table("fotos")
    op.drop_index(op.f("ix_avisos_id"), table_name="avisos")
    op.drop_index(op.f("ix_avisos_criador_id"), table_name="avisos")
    op.drop_table("avisos")
    op.drop_index(op.f("ix_autor_musica_papel"), table_name="autor_musica")
    op.drop_index(op.f("ix_autor_musica_id"), table_name="autor_musica")
    op.drop_table("autor_musica")
    op.drop_index(op.f("ix_usuarios_id"), table_name="usuarios")
    op.drop_index(op.f("ix_usuarios_email"), table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_index(op.f("ix_musicas_id"), table_name="musicas")
    op.drop_table("musicas")
    op.drop_index(op.f("ix_autores_id"), table_name="autores")
    op.drop_table("autores")
    # ### end Alembic commands ###
