"""empty message

Revision ID: d1068a8e4483
Revises:
Create Date: 2025-01-12 21:58:15.531012

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1068a8e4483"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Avisos",
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("texto", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.CheckConstraint(
            "LENGTH(texto) >= LENGTH(titulo)", name="texto_length_check"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Avisos_id"), "Avisos", ["id"], unique=False)
    op.create_table(
        "Categoria",
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Categoria_id"), "Categoria", ["id"], unique=False)
    op.create_table(
        "Usuarios",
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("senha", sa.String(length=255), nullable=False),
        sa.Column(
            "tipo_usuario",
            sa.Enum("ADMIN", "PADRAO", name="tipousuarioenum"),
            nullable=False,
        ),
        sa.Column("token_reset_senha", sa.String(length=5), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_Usuarios_email"), "Usuarios", ["email"], unique=False)
    op.create_index(op.f("ix_Usuarios_id"), "Usuarios", ["id"], unique=False)
    op.create_table(
        "Musicas",
        sa.Column("nome", sa.String(length=255), nullable=False),
        sa.Column("letra", sa.Text(), nullable=False),
        sa.Column("fk_Usuarios_id", sa.Integer(), nullable=False),
        sa.Column("fk_Categoria_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.CheckConstraint("LENGTH(letra) >= LENGTH(nome)", name="letra_length_check"),
        sa.ForeignKeyConstraint(
            ["fk_Categoria_id"],
            ["Categoria.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fk_Usuarios_id"],
            ["Usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_Musicas_fk_Categoria_id"), "Musicas", ["fk_Categoria_id"], unique=False
    )
    op.create_index(
        op.f("ix_Musicas_fk_Usuarios_id"), "Musicas", ["fk_Usuarios_id"], unique=False
    )
    op.create_index(op.f("ix_Musicas_id"), "Musicas", ["id"], unique=False)
    op.create_table(
        "Notificacoes",
        sa.Column("fk_Usuarios_id", sa.Integer(), nullable=False),
        sa.Column("titulo", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fk_Usuarios_id"],
            ["Usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_Notificacoes_fk_Usuarios_id"),
        "Notificacoes",
        ["fk_Usuarios_id"],
        unique=False,
    )
    op.create_index(op.f("ix_Notificacoes_id"), "Notificacoes", ["id"], unique=False)
    op.create_table(
        "Usuario_Aviso",
        sa.Column("fk_Usuarios_id", sa.Integer(), nullable=False),
        sa.Column("fk_Avisos_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("criado_em", sa.DateTime(), nullable=False),
        sa.Column("atualizado_em", sa.DateTime(), nullable=False),
        sa.Column("deletado_em", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fk_Avisos_id"],
            ["Avisos.id"],
        ),
        sa.ForeignKeyConstraint(
            ["fk_Usuarios_id"],
            ["Usuarios.id"],
        ),
        sa.PrimaryKeyConstraint("fk_Usuarios_id", "fk_Avisos_id", "id"),
    )
    op.create_index(
        op.f("ix_Usuario_Aviso_fk_Avisos_id"),
        "Usuario_Aviso",
        ["fk_Avisos_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_Usuario_Aviso_fk_Usuarios_id"),
        "Usuario_Aviso",
        ["fk_Usuarios_id"],
        unique=False,
    )
    op.create_index(op.f("ix_Usuario_Aviso_id"), "Usuario_Aviso", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_Usuario_Aviso_id"), table_name="Usuario_Aviso")
    op.drop_index(op.f("ix_Usuario_Aviso_fk_Usuarios_id"), table_name="Usuario_Aviso")
    op.drop_index(op.f("ix_Usuario_Aviso_fk_Avisos_id"), table_name="Usuario_Aviso")
    op.drop_table("Usuario_Aviso")
    op.drop_index(op.f("ix_Notificacoes_id"), table_name="Notificacoes")
    op.drop_index(op.f("ix_Notificacoes_fk_Usuarios_id"), table_name="Notificacoes")
    op.drop_table("Notificacoes")
    op.drop_index(op.f("ix_Musicas_id"), table_name="Musicas")
    op.drop_index(op.f("ix_Musicas_fk_Usuarios_id"), table_name="Musicas")
    op.drop_index(op.f("ix_Musicas_fk_Categoria_id"), table_name="Musicas")
    op.drop_table("Musicas")
    op.drop_index(op.f("ix_Usuarios_id"), table_name="Usuarios")
    op.drop_index(op.f("ix_Usuarios_email"), table_name="Usuarios")
    op.drop_table("Usuarios")
    op.drop_index(op.f("ix_Categoria_id"), table_name="Categoria")
    op.drop_table("Categoria")
    op.drop_index(op.f("ix_Avisos_id"), table_name="Avisos")
    op.drop_table("Avisos")
    # ### end Alembic commands ###
